# Generated by Django 3.2 on 2021-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ASN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100, null=True)),
                ("code", models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UrlList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100, unique=True)),
                ("source", models.URLField(verbose_name="Source URL")),
            ],
        ),
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(max_length=100)),
                ("lists", models.ManyToManyField(to="blocking_early_warnings.UrlList")),
            ],
        ),
    ]
