# Generated by Django 3.2 on 2021-04-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocking_early_warnings', '0003_auto_20210422_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllist',
            name='source',
            field=models.TextField(verbose_name='Content source path'),
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(default=None, null=True)),
                ('anomaly_count', models.IntegerField(default=None, null=True)),
                ('measurement_count', models.IntegerField(default=None, null=True)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocking_early_warnings.asn')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocking_early_warnings.url')),
            ],
        ),
    ]
