# Generated by Django 3.2 on 2021-04-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocking_early_warnings', '0004_auto_20210423_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
