# Generated by Django 4.0.5 on 2022-06-03 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ASN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100, null=True)),
                ("code", models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UrlList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100, unique=True)),
                ("source", models.TextField(verbose_name="Content source path")),
                (
                    "parse_strategy",
                    models.TextField(
                        choices=[
                            ("citizen_lab_csv", "Citizen Lab Csv"),
                            ("url_list_txt", "Url List Txt"),
                        ],
                        default="citizen_lab_csv",
                    ),
                ),
                (
                    "storage_type",
                    models.TextField(
                        choices=[
                            ("local_storage", "Local Storage"),
                            ("web_request", "Web Request"),
                        ],
                        default="web_request",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(max_length=100, unique=True)),
                ("lists", models.ManyToManyField(to="blocking_early_warnings.urllist")),
            ],
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.DateTimeField(default=None, null=True)),
                ("anomaly_count", models.IntegerField(default=None, null=True)),
                ("measurement_count", models.IntegerField(default=None, null=True)),
                (
                    "asn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blocking_early_warnings.asn",
                    ),
                ),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blocking_early_warnings.url",
                    ),
                ),
            ],
        ),
    ]
