# Generated by Django 3.2 on 2021-04-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocking_early_warnings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urllist",
            name="parse_strategy",
            field=models.TextField(
                choices=[
                    ("citizen_lab_csv", "Citizen Lab Csv"),
                    ("url_list_txt", "Url List Txt"),
                ],
                default="citizen_lab_csv",
            ),
        ),
    ]
