# Generated by Django 3.2 on 2021-04-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocking_early_warnings", "0002_urllist_parse_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="urllist",
            name="storage_type",
            field=models.TextField(
                choices=[
                    ("local_storage", "Local Storage"),
                    ("web_request", "Web Request"),
                ],
                default="web_request",
            ),
        ),
        migrations.AlterField(
            model_name="urllist",
            name="source",
            field=models.TextField(verbose_name="Source URL"),
        ),
    ]
