# Generated by Django 4.0.5 on 2022-06-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocking_early_warnings", "0002_url_alert_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urllist",
            name="parse_strategy",
            field=models.TextField(
                choices=[
                    ("citizen_lab_csv", "Citizen Lab Csv"),
                    ("url_list_txt", "Url List Txt"),
                ],
                default="citizen_lab_csv",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="urllist",
            name="source",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Content source path (leave blank if storage_type is db)",
            ),
        ),
        migrations.AlterField(
            model_name="urllist",
            name="storage_type",
            field=models.TextField(
                choices=[
                    ("local_storage", "Local Storage"),
                    ("web_request", "Web Request"),
                    ("db", "Db"),
                ],
                default="web_request",
            ),
        ),
    ]
