# Generated by Django 4.0.6 on 2023-03-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocking_early_warnings', '0003_alter_urllist_parse_strategy_alter_urllist_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyWarningSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days_back', models.IntegerField(default=30, verbose_name='Number of days back to check')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description_eng', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.TextField(choices=[('ok', 'Ok'), ('spike', 'Spike'), ('high_anomaly_rate', 'High Anomaly Rate')], verbose_name='Anomaly type')),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocking_early_warnings.asn', verbose_name='ASN')),
                ('metrics', models.ManyToManyField(to='blocking_early_warnings.metric', verbose_name='Offending metrics')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocking_early_warnings.url', verbose_name='Affected URL')),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='urls', to='blocking_early_warnings.site'),
        ),
    ]
