[tool.poetry]
name = "early_warnings"
version = "0.1.0"
description = ""
authors = ["Gibsy <gibsyvngr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.6"
gunicorn = "^20.1.0"
celery = "^5.2.7"
django-environ = "^0.9.0"
psycopg2 = "^2.9.3"
redis = "^4.3.4"
psycopg2-binary = "^2.9.3"
django-celery-beat = "^2.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
